# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Mongo-Docker Build
    init: docker-compose up -d

  - name: Dependencies Install&RUN
    init: npm i
    command: node index.js


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  