# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: mongo docker build
    init: docker-compose start

  - name: dependencies install
    init: gp sync-await npm i
    command: node index.js


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  