# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Copy Environment variable
    init: cp .env.example .env

  - name: Initialize DB 
    init: > 
      docker-compose up -d && npm i && gp sync-done docker-compose

  - name: Installing Dependencies
    init: gp sync-await docker-compose
    command: node index.js

  # - name: Server Start

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  