# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Copy Environment variable
    init: cp .env.example .env

  - name: Initialize DB and Dependencies
    before: docker-compose up -d
    init: npm i

  - name: Server Start
    command: node index.js


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  